#!/usr/bin/env python3
"""Generate a starter mod folder for a new MHST1 monster resource clone.

This does not magically solve table mapping. It gives modders a correct folder/manifest
layout, copies a base resource folder if supplied, and creates TODO table-patch stubs.
"""
from __future__ import annotations
import argparse, json, shutil
from pathlib import Path

def copytree_rename(src: Path, dst: Path, old_id: str, new_id: str):
    if dst.exists(): raise SystemExit(f'Destination exists: {dst}')
    for p in src.rglob('*'):
        rel=p.relative_to(src)
        parts=[x.replace(old_id,new_id) for x in rel.parts]
        out=dst.joinpath(*parts)
        if p.is_dir(): out.mkdir(parents=True, exist_ok=True)
        else:
            out.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(p,out)

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('--out', required=True, help='Output mod folder, e.g. mods/my.new.monster')
    ap.add_argument('--id', required=True, help='Manifest id, e.g. sapphin.azure_lagiacrus')
    ap.add_argument('--name', required=True, help='Readable mod name')
    ap.add_argument('--new-mo', required=True, help='New monster resource id, e.g. mo901')
    ap.add_argument('--base-mo', help='Base resource id to clone, e.g. mo048')
    ap.add_argument('--base-resource-folder', help='Existing base folder to copy, e.g. game/mod/mo/mo048')
    ap.add_argument('--species-id', type=int, default=9001)
    args=ap.parse_args()
    out=Path(args.out); out.mkdir(parents=True, exist_ok=True)
    files=[]
    if args.base_resource_folder:
        src=Path(args.base_resource_folder)
        dst=out/'files'/'mod'/'mo'/args.new_mo
        old=args.base_mo or src.name
        copytree_rename(src,dst,old,args.new_mo)
        for f in sorted(dst.rglob('*')):
            if f.is_file():
                rel=f.relative_to(out/'files').as_posix()
                files.append({'game_path':'native:/'+rel, 'source':'files/'+rel})
    (out/'tables').mkdir(exist_ok=True)
    (out/'tables'/'TODO_monster_enum_conversion_table_data.json').write_text(json.dumps({
        'target_arc':'table.arc',
        'target_entry':'table/monster_enum_conversion_table_data',
        'row_count_offset':8,
        'count_type':'u32',
        'row_base':'TODO discover with mhst1_injector.xfs info',
        'row_size':'TODO',
        'clone_rows':[{'base_index':'TODO existing similar monster row', 'set':[
            {'offset':'TODO mID offset', 'type':'u32', 'value':args.species_id},
            {'offset':'TODO mBattleEmNo offset', 'type':'u32', 'value':args.species_id},
            {'offset':'TODO mBuddyId offset', 'type':'u32', 'value':args.species_id}
        ]}]
    }, indent=2), encoding='utf-8')
    (out/'tables'/'TODO_MonsterData.json').write_text(json.dumps({
        'target_file':'battleparm/MonsterData.bin',
        'row_count_offset':0,
        'count_type':'u16',
        'row_base':2,
        'row_size':134,
        'clone_rows':[{'base_index':'TODO base enemy row', 'set':[{'offset':0,'type':'u16','value':args.species_id}]}]
    }, indent=2), encoding='utf-8')
    manifest={
        'id':args.id,
        'name':args.name,
        'version':'0.1.0',
        'priority':100,
        'description':'Starter new-monster mod generated by MHST1 New Monster Toolkit.',
        'files':files,
        'table_patches':[]
    }
    (out/'mod.json').write_text(json.dumps(manifest, indent=2), encoding='utf-8')
    (out/'README_MODDER_NOTES.md').write_text(f"""# {args.name}\n\nGenerated starter mod.\n\n## Next required work\n\n1. Verify the copied resource paths under `files/mod/mo/{args.new_mo}`.\n2. Patch `.mrl` texture references if you renamed folders/files. Use `tools/patch_mrl_paths.py`.\n3. Discover table row offsets from your real `table.arc` and `battleparm` files.\n4. Move each finished JSON patch from TODO status into `mod.json` > `table_patches`.\n5. Test with a clone of an existing monster before attempting a brand-new skeleton.\n""", encoding='utf-8')
    print(f'Created {out}')
if __name__=='__main__': main()
