#!/usr/bin/env python3
"""Scan MHST1 Remaster loose mod resources and emit a JSON/Markdown map.

Use this on folders such as the shipped `mod/` folder or extracted ARC payloads.
It recognizes the main MT Framework resource extensions used by MHST1:
  .mod model, .mrl material library, .tex texture, .lmt animation, .lcm camera, .omi object-map index.
"""
from __future__ import annotations
import argparse, json, hashlib
from pathlib import Path
from collections import defaultdict

RESOURCE_EXTS={'.mod',' .mrl','.tex','.lmt','.lcm','.omi','.ctc','.cli'}
RESOURCE_EXTS={x.strip() for x in RESOURCE_EXTS}

def magic(p: Path):
    try:
        b=p.read_bytes()[:16]
    except Exception:
        return ''
    return b[:4].decode('ascii','replace')

def strings_ascii(data: bytes, min_len=5):
    cur=[]
    for x in data:
        if 32 <= x <= 126:
            cur.append(chr(x))
        else:
            if len(cur)>=min_len:
                yield ''.join(cur)
            cur=[]
    if len(cur)>=min_len:
        yield ''.join(cur)

def mrl_refs(p: Path):
    if p.suffix.lower()!='.mrl': return []
    try: data=p.read_bytes()
    except Exception: return []
    return [s for s in strings_ascii(data,4) if ('\\' in s or '/' in s) and (s.startswith('mod') or 'tex' in s.lower())]

def scan(root: Path):
    rows=[]
    for p in sorted(root.rglob('*')):
        if not p.is_file() or p.suffix.lower() not in RESOURCE_EXTS: continue
        rel=p.relative_to(root).as_posix()
        h=hashlib.sha1(p.read_bytes()).hexdigest()[:12]
        rows.append({
            'path': rel,
            'ext': p.suffix.lower(),
            'size': p.stat().st_size,
            'magic': magic(p),
            'sha1_12': h,
            'mrl_refs': mrl_refs(p),
        })
    return rows

def write_md(rows, out: Path):
    by_top=defaultdict(list)
    for r in rows:
        by_top[r['path'].split('/')[0]].append(r)
    lines=['# MHST1 Resource Map','','Generated by `tools/resource_scan.py`.','','## Summary','']
    ext_counts=defaultdict(int)
    for r in rows: ext_counts[r['ext']]+=1
    for ext,c in sorted(ext_counts.items()): lines.append(f'- `{ext}`: {c}')
    lines += ['', '## Folders', '']
    for top,items in sorted(by_top.items()):
        lines.append(f'### `{top}`')
        ex=defaultdict(int)
        for r in items: ex[r['ext']]+=1
        lines.append(', '.join(f'`{k}`={v}' for k,v in sorted(ex.items())))
        lines.append('')
    lines += ['## Material texture references', '']
    for r in rows:
        if r['mrl_refs']:
            lines.append(f"### `{r['path']}`")
            for s in r['mrl_refs']:
                lines.append(f'- `{s}`')
            lines.append('')
    out.write_text('\n'.join(lines), encoding='utf-8')

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('root', help='Folder to scan, e.g. game/mod')
    ap.add_argument('--out-json', default='RESOURCE_MAP.json')
    ap.add_argument('--out-md', default='RESOURCE_MAP.md')
    args=ap.parse_args()
    rows=scan(Path(args.root))
    Path(args.out_json).write_text(json.dumps(rows, indent=2), encoding='utf-8')
    write_md(rows, Path(args.out_md))
    print(f'Scanned {len(rows)} resources')
if __name__=='__main__': main()
